{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    # app.kubernetes.io/managed-by: {{ .Release.Service }}
    # helm.sh/chart: {{ include "helm-app.chart" . }}
    {{- range $key, $value := .Values.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  # {{- if .Values.serviceMonitor.namespace }}
  # namespace: {{ .Values.serviceMonitor.namespace }}
  # {{- end }}
spec:
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings: {{ toYaml .Values.serviceMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      release: {{ .Release.Name }}
{{- if .Values.serviceMonitor.targetLabels }}
  targetLabels:
{{- range .Values.serviceMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
{{- end }}